# Generated by Django 4.0.4 on 2022-06-20 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=70)),
                ('examiner_link', models.CharField(max_length=25, unique=True)),
                ('test_link', models.CharField(max_length=25, unique=True)),
                ('test_instructions', models.CharField(max_length=100, unique=True)),
                ('test_file', models.FileField(upload_to='posts/%Y/%m/%d')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.IntegerField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='TestTaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100, unique=True)),
                ('student_name', models.CharField(max_length=150, unique=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_exam', to='myApp.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400, unique=True)),
                ('answer', models.CharField(max_length=100, unique=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_of_qns', to='myApp.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100, unique=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_question', to='myApp.question')),
            ],
        ),
    ]
