# Generated by Django 4.0.4 on 2022-06-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_exam_test_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='student_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testtaker',
            name='student_name',
            field=models.CharField(max_length=150),
        ),
    ]
