# Generated by Django 4.1.3 on 2023-03-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_option_option_alter_question_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtaker',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
